{
    "swagger": "2.0",
    "info": {
        "version": "v1",
        "title": "Bondora API V1",
        "description": "Bondora API version 1",
        "contact": {
            "name": "Bondora",
            "url": "https://www.bondora.com",
            "email": "investor@bondora.com"
        },
        "license": {
            "name": "Bondora Terms of Use",
            "url": "https://www.bondora.com/en/terms"
        }
    },
    "host": "api.bondora.com",
    "schemes": [
        "http"
    ],
    "paths": {
        "/api/v1/account/balance": {
            "get": {
                "tags": [
                    "Account"
                ],
                "summary": "Gets your account balance information",
                "operationId": "Account_GetBalance",
                "deprecated": false
            }
        },
        "/api/v1/account/investments": {
            "get": {
                "tags": [
                    "Account"
                ],
                "summary": "Gets list of your investments",
                "operationId": "Account_GetActive",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "Investments"
                        ]
                    }
                ]
            }
        },
        "/api/v1/eventlog": {
            "get": {
                "tags": [
                    "Account"
                ],
                "summary": "Gets events that have been made with this application (related to current access token)",
                "operationId": "Account_GetEventLog",
                "deprecated": false
            }
        },
        "/api/v1/auctions": {
            "get": {
                "tags": [
                    "Auction"
                ],
                "summary": "Gets list of active Auctions",
                "operationId": "Auction_GetActive",
                "deprecated": false
            }
        },
        "/api/v1/auction/{id}": {
            "get": {
                "tags": [
                    "Auction"
                ],
                "summary": "Gets Auction info by auction identifier",
                "operationId": "Auction_Get",
                "deprecated": false
            }
        },
        "/api/v1/bids": {
            "get": {
                "tags": [
                    "Bid"
                ],
                "summary": "Gets list of bids the investor has made.",
                "operationId": "Bid_GetBidSummaries",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "BidsRead"
                        ]
                    }
                ]
            }
        },
        "/api/v1/bid": {
            "post": {
                "tags": [
                    "Bid"
                ],
                "summary": "Makes bid(s) into specified auction(s).",
                "operationId": "Bid_MakeBids",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "BidsEdit"
                        ]
                    }
                ]
            }
        },
        "/api/v1/bid/{id}": {
            "get": {
                "tags": [
                    "Bid"
                ],
                "summary": "Get the Bid",
                "operationId": "Bid_GetBid",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "BidsRead"
                        ]
                    }
                ]
            }
        },
        "/api/v1/bid/{id}/cancel": {
            "post": {
                "tags": [
                    "Bid"
                ],
                "summary": "Cancel the Bid",
                "operationId": "Bid_CancelBid",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "BidsEdit"
                        ]
                    }
                ]
            }
        },
        "/api/v1/publicdataset": {
            "get": {
                "tags": [
                    "Report"
                ],
                "summary": "Provides daily public dataset of all loan data that is not covered by the data protection laws.",
                "operationId": "Report_GetPublicDataset",
                "deprecated": false
            }
        },
        "/api/v1/reports": {
            "get": {
                "tags": [
                    "Report"
                ],
                "summary": "List of all reports",
                "operationId": "Report_GetReportList",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "ReportRead"
                        ]
                    }
                ]
            }
        },
        "/api/v1/report/{id}": {
            "get": {
                "tags": [
                    "Report"
                ],
                "summary": "Get report data for specified report identificator.",
                "operationId": "Report_GetReport",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "ReportRead"
                        ]
                    }
                ]
            }
        },
        "/api/v1/report": {
            "post": {
                "tags": [
                    "Report"
                ],
                "summary": "Request to generate specified report type for set period.",
                "operationId": "Report_GenerateReport",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "ReportCreate"
                        ]
                    }
                ]
            }
        },
        "/api/v1/secondarymarket": {
            "get": {
                "tags": [
                    "SecondMarket"
                ],
                "summary": "Gets list of active secondary market items",
                "operationId": "SecondMarket_GetActive",
                "deprecated": false
            }
        },
        "/api/v1/loanpart/{id}": {
            "get": {
                "tags": [
                    "SecondMarket"
                ],
                "summary": "Gets LoanPartDetails info by identifier",
                "operationId": "SecondMarket_Get",
                "deprecated": false
            }
        },
        "/api/v1/loanpart/list": {
            "post": {
                "tags": [
                    "SecondMarket"
                ],
                "summary": "Gets LoanPartDetails info by identifiers in a list (up to 1000 items).",
                "operationId": "SecondMarket_GetList",
                "deprecated": false
            }
        },
        "/api/v1/secondarymarket/buy": {
            "post": {
                "tags": [
                    "SecondMarket"
                ],
                "summary": "Buy loans from secondary market.",
                "operationId": "SecondMarket_Buy",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "SmBuy"
                        ]
                    }
                ]
            }
        },
        "/api/v1/secondarymarket/sell": {
            "post": {
                "tags": [
                    "SecondMarket"
                ],
                "summary": "Sell your loans to secondary market.",
                "operationId": "SecondMarket_Sell",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "SmSell"
                        ]
                    }
                ]
            }
        },
        "/api/v1/secondarymarket/{id}/cancel": {
            "post": {
                "tags": [
                    "SecondMarket"
                ],
                "summary": "Remove your loans from secondary market.",
                "operationId": "SecondMarket_Cancel",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "SmSell"
                        ]
                    }
                ]
            }
        },
        "/api/v1/secondarymarket/cancel": {
            "post": {
                "tags": [
                    "SecondMarket"
                ],
                "summary": "Remove your loans from secondary market.",
                "operationId": "SecondMarket_CancelMultiple",
                "deprecated": false,
                "security": [
                    {
                        "oauth2": [
                            "SmSell"
                        ]
                    }
                ]
            }
        },
        "/api/v1/secondarymarket/{id}": {
            "get": {
                "tags": [
                    "SecondMarket"
                ],
                "summary": "Get the secondary market item summary",
                "operationId": "SecondMarket_GetItem",
                "deprecated": false
            }
        },
        "/api/v1/secondarymarket/list": {
            "post": {
                "tags": [
                    "SecondMarket"
                ],
                "summary": "Get the secondary market item summaries in a list",
                "operationId": "SecondMarket_GetItemList",
                "deprecated": false
            }
        }
    },
    "securityDefinitions": {
        "oauth2": {
            "type": "oauth2",
            "description": "OAuth2 Authorization Code Grant",
            "flow": "accessCode",
            "authorizationUrl": "https://www.bondora.com/oauth/authorize",
            "tokenUrl": "https://api.bondora.com/oauth/access_token",
            "scopes": {
                "Investments": "Get list of user investments",
                "BidsRead": "Get user bids",
                "BidsEdit": "Create or cancel bids",
                "SmSell": "Sell loans in Secondary Market",
                "SmBuy": "Buy loans from Secondary Market",
                "ReportCreate": "Allow to create new report(s)",
                "ReportRead": "Allow to view user's created report items and report details"
            }
        }
    },
    "security": [
        {
            "oauth2": [
            ]
        }
    ]
}